### ISSUE TITLE
Devhub Issue: About the Messaging Common Service - No Description

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/nr-messaging-service-showcase#68]
> path: (do not delete) https://github.com/bcgov/nr-messaging-service-showcase/blob/master/docs/overview.md
 > (do not delete) devhub page: https://developer.gov.bc.ca/Community-Contributed-Content/About-the-Messaging-Common-Service

## Devhub Content Issue

This file requires a description frontmatter field. Something that is 140 characters or less so that it is better experienced on the devhub. 

> sample frontmatter looks like this
```md
---
description: lorem ipsum dolor ...
---

# About the Messaging Common Service
```

**Comment by matthewhall78** [comment]
@patricksimonian I submitted a PR for this: https://github.com/bcgov/nr-messaging-service-showcase/pull/69
